### ISSUE TITLE
终端错误

### ISSUE THREAD

**Issue by ZongchengMa** [pjialin/py12306#195] opened 2019-09-17 07:10 UTC
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/Users/dillionma/Desktop/12306/py12306/py12306/app.py", line 6, in <module>
    from py12306.helpers.func import *
  File "/Users/dillionma/Desktop/12306/py12306/py12306/helpers/func.py", line 159
    def dict_count_key_num(data: dict, key, like=False):
                               ^

**Comment by pjialin** [comment] 2019-09-17 07:26
Duplicate of #14

**Closed by pjialin** 2019-09-17 07:26 UTC
