### ISSUE TITLE
有没有人报获取用户乘客列表失败的错误

### ISSUE THREAD

**Issue by luoluoppp** [pjialin/py12306#229] opened 2019-11-03 04:30 UTC
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Windows\System32\py12306\py12306\query\job.py", line 314, in check_passengers
    passengers = User.get_passenger_for_members(self.members, self.account_key)
  File "C:\Windows\System32\py12306\py12306\user\user.py", line 93, in get_passenger_for_members
    return user.get_passengers_by_members(members)
  File "C:\Windows\System32\py12306\py12306\user\job.py", line 358, in get_passengers_by_members
    self.get_user_passengers()
  File "C:\Windows\System32\py12306\py12306\user\job.py", line 343, in get_user_passengers
    return self.get_user_passengers()
  File "C:\Windows\System32\py12306\py12306\user\job.py", line 343, in get_user_passengers
    return self.get_user_passengers()
  File "C:\Windows\System32\py12306\py12306\user\job.py", line 343, in get_user_passengers
    return self.get_user_passengers()
  File "C:\Windows\System32\py12306\py12306\user\job.py", line 329, in get_user_passengers
    result = response.json()
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jhwyl\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cloudtry** [comment] 2019-11-19 06:26
你解决了吗？我也是一直获取乘客列表失败

**Comment by pjialin** [comment] 2019-11-25 07:48
Duplicate of #231

**Closed** 2019-11-25 07:49 UTC
