### ISSUE TITLE
def dict_count_key_num(data: dict, key, like=False)语法错误

### ISSUE THREAD

**Issue by Onlyonechl** [pjialin/py12306#232] opened 2019-11-21 02:23 UTC
gitpod /workspace/py12306 $ python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from py12306.app import *
  File "/workspace/py12306/py12306/app.py", line 6, in <module>
    from py12306.helpers.func import *
  File "/workspace/py12306/py12306/helpers/func.py", line 159
    def dict_count_key_num(data: dict, key, like=False):
                                                    ^
SyntaxError: invalid syntax

**Comment by pjialin** [comment] 2019-12-13 02:31
检查下 python 版本。
Duplicate of #56

**Closed by pjialin** 2019-12-13 02:31 UTC
