### ISSUE TITLE
运行时时不时会报一个错误

### ISSUE THREAD

**Issue by fenglijunnb** [pjialin/py12306#341] opened 2020-01-03 07:43 UTC
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "main.py", line 20, in main
    Query.check_before_run()
  File "D:\PYTHON\py12306\py12306\query\query.py", line 59, in check_before_run
    self = cls()
  File "D:\PYTHON\py12306\py12306\helpers\func.py", line 30, in singleton_new
    it.__init_original__(*args, **kw)
  File "D:\PYTHON\py12306\py12306\query\query.py", line 35, in __init__
    self.get_query_api_type()
  File "D:\PYTHON\py12306\py12306\query\query.py", line 154, in get_query_api_type
    self.api_type = res.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by pjialin** [comment] 2020-01-04 06:53
Duplicate of #247

**Closed by pjialin** 2020-01-04 06:53 UTC
